---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Add Flathub repository
      command: >
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Google Chrome
      command: >
        flatpak install -y flathub com.google.Chrome

    - name: Install Tidal
      command: >
        flatpak install -y flathub com.mastermindzh.tidal-hifi

    - name: Set Timezone
      command: >
        timedatectl set-timezone Europe/London

    - name: Install Boxes
      command: >
        flatpak install -y org.gnome.Boxes
    
    - name: Check if powerlevel10k directory exists
      stat:
        path: "~/powerlevel10k"
      register: powerlevel10k_directory

    - name: Install powerlevel10k
      command: >
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
      when: not powerlevel10k_directory.stat.exists
