---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Add Flathub repository
      command: >
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Google Chrome
      command: >
        flatpak install -y flathub com.google.Chrome

    - name: Install Tidal
      command: >
        flatpak install -y flathub com.mastermindzh.tidal-hifi

    - name: Set Timezone
      command: >
        timedatectl set-timezone Europe/London

    - name: Install Boxes
      command: >
        flatpak install -y org.gnome.Boxes
