---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Add Flathub repository
      command: >
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      become: yes
      become_user: lukecollins

    - name: Install Google Chrome
      command: >
        flatpak install -y flathub com.google.Chrome
      become: yes
      become_user: lukecollins

    - name: Change GTK to dark mode
      command: >
        gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
      become_user: lukecollins

