---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Add Flathub repository
      command: >
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Google Chrome
      command: >
        flatpak install -y flathub com.google.Chrome

    - name: Install Tidal
      command: >
        flatpak install -y flathub com.mastermindzh.tidal-hifi

    - name: Set Timezone
      command: >
        timedatectl set-timezone Europe/London

    - name: Install Boxes
      command: >
        flatpak install -y org.gnome.Boxes
    
    - name: Check if powerlevel10k directory exists
      stat:
        path: "~/powerlevel10k"
      register: powerlevel10k_directory

    - name: Install powerlevel10k
      command: >
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
      when: not powerlevel10k_directory.stat.exists

    - name: Change default shell of user
      become: yes
      user:
        name: "{{ lookup('env','USER') }}"
        shell: /usr/bin/zsh

    - name: Check if the fonts directory exists
      ansible.builtin.stat:
        path: "~/.local/share/fonts/MesloLGS-NF"
      register: font_dir

    - name: Create fonts directory
      ansible.builtin.file:
        path: "~/.local/share/fonts/MesloLGS-NF"
        state: directory
        mode: '0755'
      when: not font_dir.stat.exists
      register: dir_created

    - name: Download and install fonts
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "~/.local/share/fonts/MesloLGS-NF/"
      with_items:
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
      when: dir_created is changed
      register: fonts_downloaded

    - name: Rebuild font cache
      ansible.builtin.shell:
        cmd: fc-cache -f -v
      when: fonts_downloaded is changed
      register: font_cache_rebuilt

    - name: Exit Sway
      shell: "DISPLAY=:0 swaymsg exit"
      become: yes
      become_user: "{{ lookup('env','USER') }}"

